// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqthmjtbuxxcnoasaqls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdGhtanRidXh4Y25vYXNhcWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDMzMzUsImV4cCI6MjA4NzY3OTMzNX0.peBRf7ZSEjRefTMmBmWSVL_gQZZAA5UFL28bFYun0k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});